# Custom Language File - BranlyCraft Launcher

[ejs.app]
title = "BranlyCraft"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"
